name: dcin_cqg
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - cudatoolkit=11.8.0
  - cudnn=8.9.2.26
  - cupti=11.8.0
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libffi=3.4.4
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libprotobuf=4.25.3
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - lightning-utilities=0.9.0
  - magma=2.7.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.15
  - pip=24.2
  - pybind11-abi=4
  - python=3.9.20
  - pytorch-lightning=2.3.0
  - pyyaml=6.0.2
  - readline=8.2
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchmetrics=1.4.0.post0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - albucore==0.0.20
      - albumentations==1.4.21
      - annotated-types==0.7.0
      - basicsr==1.4.2
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - efficientnet-pytorch==0.7.1
      - eval-type-backport==0.2.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - fsspec==2024.10.0
      - future==1.0.0
      - grpcio==1.68.1
      - huggingface-hub==0.26.2
      - idna==3.10
      - imageio==2.36.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lmdb==1.5.1
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - monai==1.4.0
      - munch==4.0.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - packaging==24.2
      - pillow==11.0.0
      - platformdirs==4.3.6
      - pretrainedmodels==0.7.4
      - protobuf==5.29.1
      - pycocotools==2.0.8
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyparsing==3.2.0
      - python-color-transfer==0.1.2a0
      - python-dateutil==2.9.0.post0
      - realesrgan==0.3.0
      - requests==2.32.3
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - segmentation-models-pytorch==0.3.4
      - simsimd==6.0.5
      - six==1.16.0
      - stringzilla==3.10.10
      - sympy==1.13.1
      - tb-nightly==2.19.0a20241121
      - tensorboard-data-server==0.7.2
      - tifffile==2024.8.30
      - timm==0.9.7
      - tomli==2.2.1
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.67.0
      - triton==3.0.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - werkzeug==3.1.3
      - yapf==0.43.0
      - zipp==3.21.0
